name: github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  setup-cosa-command:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: install docker
        run: |
          sudo apt update
          sudo apt remove containerd.io
          sudo apt install -y make git docker.io
          sudo systemctl enable --now docker
      - name: Checkout k3s source
        uses: actions/checkout@v4
        with:
          repository: ningmingxiao/k3s
          path: ./k3s-src

      - name: Build with make
        run: |
          cd ./k3s-src
          make binary